---
# --------------------------------------------------------------------------
# Setup
# --------------------------------------------------------------------------
- name: Preset variables for test resource names
  ansible.builtin.set_fact:
    organization_name: "RTA-Org-{{ rh_username }}"
    team_name_prefix: "RTA-Team-{{ rh_username }}"
    org1: "RTA-Org-rothakur-1"
    org2: "RTA-Org-rothakur-2"
    org3: "RTA-Org-rothakur-3"
    org4: "RTA-Org-rothakur-4"
    team1: "RTA-Team-rothakur-1"
    team2: "RTA-Team-rothakur-2"
    team3: "RTA-Team-rothakur-3"
    team4: "RTA-Team-rothakur-4"

# --------------------------------------------------------------------------
# Organizations
# --------------------------------------------------------------------------
- name: Create Organization 1
  ansible.platform.organization:
    name: "{{ org1 }}"
    aap_hostname: "{{ aap_hostname }}"
    aap_username: "{{ aap_username }}"
    aap_password: "{{ aap_password }}"
    aap_validate_certs: false
  register: org1

- name: Create Organization 2
  ansible.platform.organization:
    name: "{{ org2 }}"
    aap_hostname: "{{ aap_hostname }}"
    aap_username: "{{ aap_username }}"
    aap_password: "{{ aap_password }}"
    aap_validate_certs: false
  register: org2

- name: Create Organization 3
  ansible.platform.organization:
    name: "{{ org3 }}"
    aap_hostname: "{{ aap_hostname }}"
    aap_username: "{{ aap_username }}"
    aap_password: "{{ aap_password }}"
    aap_validate_certs: false
  register: org3

- name: Create Organization 4
  ansible.platform.organization:
    name: "{{ org4 }}"
    aap_hostname: "{{ aap_hostname }}"
    aap_username: "{{ aap_username }}"
    aap_password: "{{ aap_password }}"
    aap_validate_certs: false
  register: org4

- name: Assert organizations were created
  ansible.builtin.assert:
    that:
      - org1 is changed
      - org2 is changed
      - org3 is changed
      - org4 is changed

# --------------------------------------------------------------------------
# Teams
# --------------------------------------------------------------------------
- name: Create Team 1 in Organization 1
  ansible.platform.team:
    name: "{{ team1 }}"
    organization: "{{ org1.name }}"
    description: "Test Team 1"
    aap_hostname: "{{ aap_hostname }}"
    aap_username: "{{ aap_username }}"
    aap_password: "{{ aap_password }}"
    aap_validate_certs: false
  register: team1

- name: Create Team 2 in Organization 2
  ansible.platform.team:
    name: "{{ team2 }}"
    organization: "{{ org2.name }}"
    description: "Test Team 2"
    aap_hostname: "{{ aap_hostname }}"
    aap_username: "{{ aap_username }}"
    aap_password: "{{ aap_password }}"
    aap_validate_certs: false
  register: team2

- name: Create Team 3 in Organization 3
  ansible.platform.team:
    name: "{{ team3 }}"
    organization: "{{ org3.name }}"
    description: "Test Team 3"
    aap_hostname: "{{ aap_hostname }}"
    aap_username: "{{ aap_username }}"
    aap_password: "{{ aap_password }}"
    aap_validate_certs: false
  register: team3