---
- name: TC-ORG-001 - Verify that the organization module creates a new organization in the
  hosts: localhost
  gather_facts: false

  vars:
    # Change this to your Red Hat username so names are unique
    rh_username: "{{ lookup('env', 'USER') | default('testuser', true) }}"
    org_name: "TestOrg-1-{{ rh_username }}"

  tasks:
    # First deletion
    - name: Create organization TC-ORG-001
      ansible.platform.organization: &tc_org_001
        name: "{{ org_name }}"
        description: Primary engineering tenant
        state: present
        aap_hostname: <URL for your instance>
        aap_username: <username>
        aap_password: <password>
        aap_validate_certs: false
      register: add_org_first

    - name: Assert rename was successful
      ansible.builtin.assert:
        that:
          - add_perm is changed

    - name: Re-run task to verify idempotency
      ansible.platform.role_definition: *tc_org_001
      register: add_org

    - name: Assert second run is idempotent (no changes)
      ansible.builtin.assert:
        that:
          - add_team is not changed
