---
- name: TC-ORG-001 - Verify that the organization module creates a new organization in the
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/user.yml
    - ./vars/aap.yml
  vars:
    org_name: "TestOrg-1-{{ rh_username }}"

  tasks:
    - name: Cleanup
      ansible.builtin.include_tasks: ./reset/TC-ORG-001.yaml

    - name: Create organization TC-ORG-001
      ansible.platform.organization: &tc_org_001
        name: "{{ org_name }}"
        description: Primary engineering tenant
        state: present
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        aap_validate_certs: false
      register: add_org_first

    - name: Assert operation was successful
      ansible.builtin.assert:
        that:
          - add_org_first is changed

    - name: Create organization TC-ORG-001
      ansible.platform.organization: *tc_org_001
      register: add_org_idem

    - name: Assert second run is idempotent (no changes)
      ansible.builtin.assert:
        that:
          - add_org_idem is not changed
    
