---
- name: TC-RDEF-002 - Rename role while preserving other fields
  hosts: localhost
  gather_facts: false

  vars:
    # Change this to your Red Hat username so names are unique
    rh_username: "{{ lookup('env', 'USER') | default('testuser', true) }}"
    old_role_name: "TestRole-1-{{ rh_username }}"
    new_role_name: "TestRole-1-Renamed-{{ rh_username }}"

  tasks:
    - name: Rename role definition while preserving fields
      ansible.platform.role_definition:
        name: "{{ old_role_name }}"
        new_name: "{{ new_role_name }}"
        content_type: awx.inventory
        permissions:
          - awx.view_inventory
        state: present
        aap_hostname: "<URL for your instance>"
        aap_username: "<username>"
        aap_password: "<password>"
        aap_validate_certs: false
      register: rename_result

    - name: Assert rename was successful
      ansible.builtin.assert:
        that:
          - rename_result is changed

    - name: Re-run rename task to verify idempotency
      ansible.platform.role_definition:
        name: "{{ old_role_name }}"
        new_name: "{{ new_role_name }}"
        content_type: awx.inventory
        permissions:
          - awx.view_inventory
        state: present
        aap_hostname: "<URL for your instance>"
        aap_username: "<username>"
        aap_password: "<password>"
        aap_validate_certs: false
      register: rename_result_check

    - name: Assert second run is idempotent (no changes)
      ansible.builtin.assert:
        that:
          - rename_result_check is not changed
