---
- name: TC-RTA-001 - Role team assignment
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/user.yml
    - ./vars/aap.yml
  tasks:
    - name: Cleanup
      ansible.builtin.include_tasks: ./reset/TC-RTA-001.yaml
    
    - name: precondition
      ansible.builtin.include_tasks: ./precondition/TC-RTA-001.yaml
    
    - name: Assign Org Inventory Admin to Team2 on Org1
      ansible.platform.role_team_assignment: &tc_rta_001
        team: "{{ team1.name }}"
        assignment_objects:
        - object_ansible_id: "{{ org1.name }}"
        role_definition: Organization Inventory Admin
        state: present
      register: org_admin_assignment_1

    - name: Assert rename was successful
      ansible.builtin.assert:
        that:
          - org_admin_assignment_1 is changed

    - name: Re-run rename task to verify idempotency
      ansible.platform.role_team_assignment: *tc_rta_001
      register: idem

    - name: Assert second run is idempotent (no changes)
      ansible.builtin.assert:
        that:
          - idem is not changed
