---
- name: TC-RDEF-003 - Update Description Only
  hosts: localhost
  gather_facts: false

  vars:
    # Change this to your Red Hat username so names are unique
    rh_username: "{{ lookup('env', 'USER') | default('testuser', true) }}"
    role_name: "TestRole-1-Renamed-{{ rh_username }}"

  tasks:
