---
- name: TC-USER-001 - Create user and associate to org & team
  hosts: localhost
  gather_facts: false
  vars_files:
    - ./vars/user.yml
    - ./vars/aap.yml
  vars:
    # Per-user uniqueness when many folks share one AAP
    user_name: "TestUser-1-{{ rh_username }}"
    first_name: "User-1"
    last_name: "Test"
    user_password: "ansible"
    email: "testuser1@local.com"
    # org_name: "TestOrg-1-{{ rh_username }}"
    # team_name: "TestOrg-1-{{ rh_username }}"
  tasks:
    - name: Cleanup
      ansible.builtin.include_tasks: ./reset/TC-USER-001.yaml
    # --- Create the user ---
    - name: Create user in Gateway
      ansible.platform.user: &tc_user_001
        username: "{{ user_name }}"
        first_name: "{{ first_name }}"
        last_name:  "{{ last_name }}"
        email: "{{ email }}"
        password: "{{ user_password }}"
        state: present
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        aap_validate_certs: false
      register: create_user

    - name: Assert user was created (first run)
      ansible.builtin.assert:
        that: create_user is changed
        fail_msg: "User was not created as expected on first run."
    
    - name: Assert operation was successful
      ansible.builtin.assert:
        that:
          - add_user_first is changed

    - name: Create User TC-USER-001
      ansible.platform.organization: *tc_user_001
      register: add_user_idem

    - name: Assert second run is idempotent (no changes)
      ansible.builtin.assert:
        that:
          - add_user_idem is not changed
    